[tool.pylint.messages_control]
disable = [
    "C0114",  # missing-module-docstring
    "C0115",  # missing-class-docstring
    "C0116",  # missing-function-docstring
    "W0511",  # fixme
    "W0621",  # redefined-outer-name
    "W0703",  # broad-except
    "W0612",  # unused-variable
    "W0613",  # unused-argument
    "C0301",  # line-too-long
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.master]
ignore = ["venv", "__pycache__", ".git"]

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_", "id", "db"] 